Config = {
    Debug = true,
    Core = "QBCore",
    Framework = "qb-core",
    PlayerUnload = "QBCore:Client:OnPlayerUnload",
    PlayerLoad = "QBCore:Client:OnPlayerLoaded",
    UsingQBWeapons = false,
    PlayerSlots = 40,

    restrictedBags = {
        [40] = true,
        [41] = true,
        [44] = true,
        [45] = true,
        [81] = true,
        [82] = true,
        [85] = true,
        [86] = true,
        [126] = true,
        [127] = true
    },
    
    restrictedUndershirts = {
        [252] = true,
        [253] = true,
        [254] = true
    },

    BackItems = {
        ["MARKEDBILLS"] = {
            model="prop_money_bag_01",
            quantity=1,
            back_bone = 24818,
            x = -0.6,
            y = -0.17,
            z = -0.12,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["BACKPACK1"] = {
            model="prop_beach_bag_01a",
            quantity=1,
            back_bone = 24818,
            x = 0.0,
            y = -0.1,
            z = -0.0,
            x_rotation = 90.0,
            y_rotation = 0.0,
            z_rotation = 0.0,
        },
    
        -- AK74
        ["WEAPON_AK74"] = {
            model="w_ar_ak74",
            back_bone = 24818,
            x = -0.05,
            y = -0.15,
            z = 0.1,
            x_rotation = 0.0,
            y_rotation = 0.0,
            z_rotation = 0.0,
        },
    
        ["CERBERUS_CHAIN"] = {
            model="cerberus_chain",
            back_bone = 24818,
            x = 0.18,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["SEASIDE_CHAIN"] = {
            model="seaside_chain",
            back_bone = 24818,
            x = 0.18,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["CG_CHAIN"] = {
            model="cg_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        -- ["GARCIA_CHAIN"] = {
        --     model="garcia_chain",
        --     back_bone = 24818,
        --     x = 0.10,
        --     y = 0.07,
        --     z = 0.0,
        --     x_rotation = 180.0,
        --     y_rotation = 90.0,
        --     z_rotation = 0.0,
        -- },
    
        ["GULAG_CHAIN"] = {
            model="gulag_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["BALLAS_CHAIN"] = {
            model="BALLAS_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["ST_CHAIN"] = {
            model="st_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["RUST_CHAIN"] = {
            model="rust_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["HYDRA_CHAIN"] = {
            model="hydra_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["WSB_CHAIN"] = {
            model="wsb_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["SAINTS_CHAIN"] = {
            model="saints_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["ESV_CHAIN"] = {
            model="esv_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["KOIL_CHAIN"] = {
            model="koil_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["KOIL_CHAIN2"] = {
            model="koil_chain",
            back_bone = 24818,
            x = 0.10,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["MDM_CHAIN"] = {
            model="mdm_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["GSF_CHAIN"] = {
            model="gsf_chain",
            back_bone = 24818,
            x = 0.17,
            y = 0.07,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["ESM_CHAIN"] = {
            model="esm_chain",
            back_bone = 24818,
            x = 0.16,
            y = 0.06,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["CRIPS_CHAIN"] = {
            model="crips_chain",
            back_bone = 24818,
            x = 0.16,
            y = 0.06,
            z = 0.0,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
        ["WEAPON_SMG"] = {
            model="w_sb_smg", 
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = -0.12,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
    
        ["WEAPON_BULLPUPRIFLE"] = {
            model="w_ar_bullpuprifle",
            quantity=1,
            back_bone = 24818,
            x = 0.15,
            y = -0.15,
            z = 0.15,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
    
        ["WEAPON_LTL"] = {
            model="w_sg_ltl",
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
    
        ["WEAPON_GUSENBERG"] = {
            model="w_sb_gusenberg",
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.01,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
    
        ["WEAPON_ASSAULTSMG"] = {
            model="w_sb_assaultsmg",
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = -0.12,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_MICROSMG"] = {
            model="w_sb_microsmg",
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.1,
            x_rotation = 0.0,
            y_rotation = 0.0,
            z_rotation = 0.0,
        },
        ["WEAPON_SPECIALCARBINE"] = {
            model="w_ar_specialcarbine", 
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_CARBINERIFLE"] = {
            model="w_ar_carbinerifle", 
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_CARBINERIFLE_MK2"] = {
            model="w_ar_carbineriflemk2", 
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_RPG"] = {
            model="w_lr_rpg", 
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_GROZA"] = {
            model="w_ar_groza",
            quantity=1,
            back_bone = 24818,
            x = 0.1,
            y = -0.15,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["COKEBRICK"] = {
            model="bkr_prop_coke_cutblock_01", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
        },
        ["WEED_AK47_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEED_PURPLE_HAZE_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEED_WHITE_WIDOW_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEED_SKUNK_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEED_OG_KUSH_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEED_AMNESIA_SEED"] = {
            model="bkr_prop_weed_drying_01a", 
            quantity=1,
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["WEAPON_SCAR"] = {
            model="w_ar_scar",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_SPECIALCARBINE_MK2"] = {
            model="w_ar_scar",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_HEAVYSNIPER"] = {
            model="w_sr_heavysniper",
            back_bone = 24818,
            x = -0.2,
            y = -0.17,
            z = -0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_KATANA"] = {
            model="w_me_katana_lr",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.05,
            x_rotation = 235.0,
            y_rotation = 8.0,
            z_rotation = 100.0,
        },
        ["WEAPON_KATANAS"] = {
            model="w_me_katana_lr",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.05,
            x_rotation = 235.0,
            y_rotation = 8.0,
            z_rotation = 100.0,
        },
        ["WEAPON_SLEDGEHAM"] = {
            model="w_me_sledgeham",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.15,
            x_rotation = 145.0,
            y_rotation = 8.0,
            z_rotation = 80.0,
        },
        ["WEAPON_COMBATPDW"] = {
            model="w_sb_mpx",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_COMPACTRIFLE"] = {
            model="w_ar_draco",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_M4"] = {
            model="w_ar_M4", 
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.09,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_M6IC"] = {
            model="w_ar_M4", 
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.09,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_M14"] = {
            model="w_sr_m14", 
            back_bone = 24818,
            x = -0.2,
            y = -0.17,
            z = -0.15,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_M14"] = {
            model="w_sr_m14", 
            back_bone = 24818,
            x = -0.05,
            y = -0.17,
            z = -0.0001,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_DRAGUNOV"] = {
            model="w_sr_dragunov", 
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = -0.0001,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_ASSAULTRIFLE"] = {
            model="w_ar_assaultrifle", 
            back_bone = 24818,
            x = 0.0,
            y = -0.14,
            z = 0.05,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_ASSAULTRIFLE2"] = {
            model="w_ar_assaultrifle2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_GEPRARD"] = {
            model="w_ar_gepard", 
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_MICROSMG2"] = {
            model="w_sb_uzi", 
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_MICROSMG3"] = {
            model="w_sb_microsmg3", 
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_ADVANCEDRIFLE"] = {
            model="w_ar_groza",
            back_bone = 24818,
            x = 0.1,
            y = -0.17,
            z = 0.1,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["WEAPON_MACHETE"] = {
            model="w_me_machette_lr", 
            back_bone = 24817,
            x = 0.01,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 120.0,
            z_rotation = 0.0,
        },
    }
}